service: aws-node-typscript
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: handler.hello
  getUser:
    handler: getUser.handler

plugins:
  - serverless-esbuild
